events {}

http {
    # Upstream tiap service internal (hanya bisa diakses lewat gateway)
    upstream mahasiswa_service {
        server mahasiswa-service:8000;
    }
    upstream krs_service {
        server krs-service:8000;
    }
    upstream kurikulum_nilai_service {
        server kurikulum-nilai-service:8000;
    }

    server {
        listen 80;
        server_name _;

        # Header yang diteruskan ke semua service
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization     $http_authorization;
        proxy_set_header X-IAE-KEY         $http_x_iae_key;
        proxy_set_header X-API-KEY         $http_x_api_key;

        # === Routing Hub berdasarkan resource ===
        # Service A - Mahasiswa
        location /api/v1/mahasiswa {
            proxy_pass http://mahasiswa_service;
        }

        # Service A - Auth (SSO Login & Profile)
        location /api/v1/auth {
            proxy_pass http://mahasiswa_service;
        }

        # Service B - KRS
        location /api/v1/krs {
            proxy_set_header Host $proxy_host;
            proxy_pass http://krs_service;
        }

        # Service C - Nilai & Kurikulum
        location /api/v1/kurikulum {
            proxy_set_header Host $proxy_host;
            proxy_pass http://kurikulum_nilai_service;
        }
        location /api/v1/nilai {
            proxy_set_header Host $proxy_host;
            proxy_pass http://kurikulum_nilai_service;
        }

        # Info gateway
        location = / {
            default_type application/json;
            return 200 '{"gateway":"IAE Kelompok 9","services":["/api/v1/auth/token","/api/v1/mahasiswa","/api/v1/mahasiswa/{nim}/matkul","/api/v1/krs","/api/v1/kurikulum","/api/v1/nilai"]}';
        }
    }
}
